### ISSUE TITLE
Slider customization

### ISSUE THREAD

**Issue by ksenia-lyagusha** [ngodacdu/SSSlider#1]
Is it possible to use this slider as a native UISlider? What I mean: manually set a needed value to the slider or from very beginning the slider start moving and has an opportunity to set start/end time value.  
It'd be very useful info for me. Thanks :-)

**Comment by ngodacdu** [comment]
@ksenia-lyagusha Thanks for your suggestion. I have updated that feature in version 1.0.2. Now, u can use. Please continue to share with me if u have any more suggestions. Thanks.
